apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-projects
  namespace: argocd
  labels:
    app.kubernetes.io/instance: application-of-applications
  # don't enable finalizer otherwise it'll cause a cascading delete of projects if this app is removed
spec:
  project: default
  source:
    path: argocd/projects
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: helming
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
