apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/instance: application-of-applications
  # don't enable finalizer otherwise it'll cause a cascading delete of projects if this app is removed
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: applications
  source:
    path: argocd/apps/monitoring
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
