apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-websites
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  # project: applications
  source:
    path: argocd/apps/websites
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
