apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-monitoring
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # project: applications
  source:
    path: argocd/apps/monitoring
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
