apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-argocd
  namespace: argocd
  labels:
    app.kubernetes.io/instance: application-of-applications
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: argocd/apps/argocd
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    # repoURL: https://github.com/Vanderscycle/Professional-website.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
