apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - application-root.yaml
  - application-git.yaml
  - application-cicd.yaml
  - application-secrets.yaml
  - application-projects.yaml
  - application-argocd-plugins.yaml
