apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - application-root.yaml
  # - application-git.yaml
  # - application-argocd.yaml
  - application-cicd.yaml
  - application-vault.yaml
  - application-secrets.yaml
  - application-projects.yaml
configMapGenerator:
  - name: argocd-cm
    literals:
      - kustomize.buildOptions="--enable-helm --load-restrictor LoadRestrictionsNone"
