apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
    app.kubernetes.io/instance: application-of-applications

namespace: argocd

resources:
  # - application-root.yaml # argocd
  - application-servers.yaml
  # - application-monitoring.yaml
  - application-cloud.yaml
  - application-secrets.yaml
  - application-projects.yaml
  - application-support.yaml
  # - application-argocd.yaml
  - application-website.yaml
