apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#     app.kubernetes.io/component: databases
#     app.kubernetes.io/instance: postgres
#     app.kubernetes.io/name: postgres

# namespace: postgres

resources:
  - namespace.yaml
  - ../../base

helmCharts:
  - name: postgresql
    version: 12.1.6
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    namespace: postgres
    releaseName: db
