apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime-kuma

resources:
  - certificate.yaml

commonLabels:
  app.kubernetes.io/name: uptime-kuma
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/instance: uptime-kuma
  app.kubernetes.io/part-of: infrastructure

# labels:
#   - pairs:
#       app.kubernetes.io/component: uptime-kuma
#     includeTemplates: true

helmCharts:
  - name: uptime-kuma
    version: 2.16.0
    repo: https://dirsigler.github.io/uptime-kuma-helm
    valuesFile: values.yaml
    namespace: uptime-kuma
    releaseName: monitoring
