apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorio
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: factorio
    server: https://kubernetes.default.svc
  project: factorio
  source:
    path: charts/servers/factorioSpaceEx
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: main
  #   chart: factorio-server-charts
  #   repoURL: https://sqljames.github.io/factorio-server-charts/
  #   targetRevision: 1.2.0
  #   helm:
  #     releaseName: factorio
  #     valueFiles:
  #       - custom-values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
