apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: git
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for gitea
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # source:
  #   plugin:
  #     name: kustomize-build-with-helm

  destinations:
    - namespace: git
      server: https://kubernetes.default.svc
    - namespace: secrets
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:Vanderscycle/infrastructure.git
