apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for vault
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: consul
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:Vanderscycle/infrastructure.git
    - https://github.com/hashicorp/consul
    - https://github.com/hashicorp/consul-k8s
    - https://helm.releases.hashicorp.com/
