apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for parent applicatons used when employing app of apps
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: 'argoproj.io'
      kind: 'AppProject'
  namespaceResourceWhitelist:
    - group: "argoproj.io"
      kind: Application
  sourceRepos:
    - "git@github.com:vancycles-industries/infrastructure.git"
  sourceNamespaces:
    - "argocd"
    - "kube-system"

