apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secrets
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for secrets
  destinations:

    - namespace: "*"
      server: "*"
    # - namespace: secrets
    #   server: https://kubernetes.default.svc
    # - namespace: kube-system
    #   server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
    # - git@github.com:Vanderscycle/infrastructure.git
    # - https://github.com/bitnami-labs/sealed-secrets
