apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: servers
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for servers (factorio)
  destinations:
    - namespace: servers
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - git@github.com:Vanderscycle/infrastructure.git

