apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for cloud tools
  destinations:
    - namespace: '*'
      server: '*'
    - namespace: nextcloud
      server: https://kubernetes.default.svc
    - namespace: postgres
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - git@github.com:Vanderscycle/infrastructure.git
