apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for monitoring
  destinations:
    - namespace: "*"
      server: "*"
    # - namespace: uptime-kuma
    #   server: https://kubernetes.default.svc
    # - namespace: prometheus
    #   server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
    # - git@github.com:Vanderscycle/infrastructure.git
    # - https://prometheus-community.github.io/helm-charts
    # - https://github.com/prometheus-community/helm-charts.git
