apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: A factorio server
  destinations:
    - namespace: factorio
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - '*'
    # - git@github.com:Vanderscycle/infrastructure.git

