apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: websites
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for hosted websites
  destinations:
    - namespace: precisionHub 
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "git@github.com:vancycles-industries/infrastructure.git"
    - "git@github.com:vancycles-industries/precisionHubMonorepo.git"
  sourceNamespaces:
    - "precisionHub"
    - "kube-system"
