apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: websites
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for hosted websites
  destinations:
    - namespace: "*"
      server: "*"
    # - namespace: professional-web-frontend
    #   server: https://kubernetes.default.svc
    # - namespace: kube-system
    #   server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
    # - git@github.com:Vanderscycle/infrastructure.git
    # - git@github.com:Vanderscycle/Professional-website.git
