apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure declarative config for argocd (self management)
  destinations:
    - namespace: "*"
      server: "*"
    # - namespace: argocd
    #   server: https://kubernetes.default.svc
    # - namespace: kube-system
    #   server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
