apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for parent applicatons used when employing app of apps pattern
  sourceRepos:
    - git@github.com:Vanderscycle/infrastructure.git
  # Allow this project to deploy only to 'argocd' namespace
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  # Deny all namespace-scoped resources from being created, except for Application
  namespaceResourceWhitelist:
    - group: "argoproj.io"
      kind: Application
