apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
patches:
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: main
    target:
      kind: Application
      name: .*
