apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
patches:
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: main
    target:
      kind: Application
      name: .*
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: argocd-server
      namespace: argocd
      version: v1
  - patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: "--enable-helm"
    target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
      version: v1
