apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8s
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  project: support
  source:
    chart: n8n
    repoURL: oci://8gears.container-registry.com/library/n8n
    targetRevision: 0.23
    helm:
      releaseName: n8n 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
