apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8s
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  project: support
  source:
    path: charts/support/n8n
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
