---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vanilla-factorio-admin-secret
  namespace: factorio-vanilla
spec:
  encryptedData:
    token: AgAIqHL+RQJXbeQcBPvIeWPXipT96ipohOTphRFACm5LzjDycBN+lyn8CSOhOXQktmANs0w26LY1rRqPDPA01l10NF9UARjjng/E5XRzBqYBZWOGLEP8lF1pwP5lZLNBMrhHF7KfXwidya/16/75Bz9pi7EAjVat142yxlLSQu3X6Zta18JphxkSwdEd/1p4HE62XLZR/dT8Be1rn7V+DX/tgSjcC3d5LqvtjkjUkbD8HNKnBXZA4EpZxGidhfVIZE95Rpt7rX7hOjEcyyUGNGD0bhLF9wYZOsUuM9Rzk3dDcQtvVhQhXG4vU6NkOEQV41jsjPEfXOr63gGXU2DgePBYbaVeLFaZtb9s0teAZZHvXodWU6fqCH4m189Fis7ZKwckQ+5dzMgVD8FvyFQzYc5mDCknRWQY2Be3+YMoVF+du8bg1pj1isEu7Gdggn70I17nSoPZf5sU80+IRsSkTSKo39v6h2drE4+ECtdaCfu1gjP1a/c/ITig5WZHmNScT7bEFBZt2rNh/rY0msEbubjrPUCMcZdb0K+RV0sbPvGAkMr70JKNldyvofxAhFX5uZRPgVziAzxO3U2gdp343d3BagMv4k/A3DJHbepnTr5YC5ZvVMVZNYL6hTnICiiLyTKsVbRnb6qxC3fzdSFX4vBoQBg1T9/9YGDYke2PfoWetkDtFgp7GP5CO23/Idm8L7rZ7lvhmSIGf4Y+hdAvlnDlrwpwb1KR5v1PrFWSRq9E
    username: AgAgGfQsX5u4527DJ2peSrRG6xwKQZp1GT2RkcI2miwdHoQwXg7ziFlmNAfFHjLAGVKHB133Z6ndAudtKdx9P+a8Q6Tel2KDijn4QGTCnYY8AWNfHErdJGQWnAztQnK76q1DIXqlecXpjXmMTf+utkAKfse0F7wDDQpKyetQ+yma8o2hNP/51RJWqETQMnPHY9iO7XDOSWhXXSw80QR2PcrrDNm0+fD4kpPXKLo0GXN/BoCm/lkdzVgC0Ymn6aTV34jGPI+/ZEAQcxRh3aDDlkrcgZEeFzSjo0dL3i6wL/sjzkTZAuFIZuHOB9WtJF5dx9PxJiuqyYu1llMCGfhO2CQCHxh0DjRtkbTKyAqVLktuMP3KXS/sUgfDWxQDpvI2evS6G4kWlXVbm/SBqMlAAmx/ZsCdh7ip7j9rGk78Ylf0yNunile80X1iVTHhFM15tuazTi8f1jJZ57Aymhzy3n1GV4upoFoUR9lWlNMKx8vR7zHhk5EgbmtUt0Y6L9J9d/nTfDO7zyUmCyvOGNhVyjPXVbjljfLzELo+vhH3nihi77if0CfIQ844791Iq+btrjDMMFpELt8vre3Q2bOvwb0VTe2Puia8wb03tbbbwaWnca+cT1pUAF7tLtx2k/p2MN7oTTOhTZNoqzyytmaYtHk60H7dyEON0jUU9EZPHkbNubxqajrLvB1WpwTWIcodDR67vWm+X4ETaoHv5SU=
  template:
    metadata:
      creationTimestamp: null
      name: vanilla-factorio-admin-secret
      namespace: factorio-vanilla
