apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/monitoring/prometheus/crds/
    targetRevision: kube-prometheus-stack-44.3.1
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: charts/monitoring/prometheus
    repoURL: git@github.com:Vanderscycle/infrastructure.git
    targetRevision: main
    helm:
      skipCrds: true
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
