apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  - name: external-dns
    version: 6.13.1
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    namespace: external-dns
    releaseName: dns
