apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgAlLdCGbCBStb/umC+qsr3gxjQPY2UhPfa69miSYPtX/LF9B8KcBeDUOplSqF07l7iIRf0Ccibc0vnV6gzdPVH17UURwO7ArG3Lm7z/ZIRUivf8gTOHTbLSq1Hu8FWCOAkEJh2eERMO6x4VPlY2FbR+6oEgCn4v6w8t9dWzDDDrxcOlPLAPQCfcn4PBJnY4BgGxbk4KtBCTCXr7Guw9eBjcOz2WuKscp8YJOpteQLz+0lyLAKbIUmZDy1sXG+4Cqqx6U+fqS9ohEelPCmBsk/fJH8Qu5XcYgJNRUNmn0kPJr3v0m2d+Y/x2grpu9zCGI+aL5TYjGZgAhrvO6DWbwTzvl+qDd+OV3Ggtv8lbUTlXRv5v3cdzBoPm4AsfLfRkhyXWhjIWJ/Zt8dZuCQcrfK8f3q70AYPeeGKMB68lIifcdzAyfFY4WXY/l0avoVqK5ZN8uYAHdPHLH7CTq05oR4gC8n9z0uolke9NI4A0sZSy+OyfjvIPSJdVWITLE4ILG6G4uY95DfmlS1fGChBcqj3HcFJmbckiMzFMBgOzhoodXJMdBo7Q4YgpCsc3iQHPxTzlFNk7oKiTmPW8SAAmQndJhdyW67kjSbu9Brfe3B2cOj438NzbUwhTSEBRuSMxJ78V+YIZVh520gG8us9cQDE7srFH9y9/wrUvMyRHdZmJaoNGuqyHZ+xoGVmv6GTSQdPqQ/NTR8kN+g9LLn/DlDxUSQdBHDViTtfaoZKX1VT9oQE=
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
