---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCTu/MPYQlH46TEVAl9bid6gEb7G/WuGB7zb6MpH2CQ9JQBTK/3y1KyIEkW7HO5GdYOAT4ao9OekpMxNV7LDQe2JI5VQPcL2vIbAviCOIpTUn9H8TV1AJxfo2d7pJ0355C3D3QkWQWSAOuvHhXr0refTwbuPRCAKwdP90k+awWumxVy9tGi6vCG36svM0PwF5Ls4XEvZTClw2OFwO3dP5gTr7phq2TorH59CjH0EVCi2G6AmRJXqf1bEkvTJeMC9M9zYslRuJsAbiNdGmSX5/UZHSJf/vTbbKaUjgbUMMJERexl4tPx4Eow4R92MrKPs8VZE3fKQ+87VCV/cxMJn9WteHjH9V/LlTRLyLxmPjlAKLCONA00RH1T4YBDbj2ASVX74WBq4j3wUjbUhXyvIpP4uultN9lxFbV9BadC8NB10HBO6JhkU6hhgGtZ2zeOX6qiGYDSPBoymF6pnJLc2FScPb/efiN2sN8qEeiZ0yySG7/jIw3qdc9WcgM2YDqPRHcAgBZibt/iHHkzEnP0bSLtw/06hzVhLKvx4h31HKVFryCj2tXw0pArbEyoSgqTwTr8YglkozzmkWWZ5xBlJMtcsaXC2OMdE28jtFRWxILbzam64zxQaFnRTZJxKVofie0Zjgr84wrHvEzCNH7yr8hvclaWgYjXp5bJV36xOWJf6w84o0Czjj1c258afuzyl2RtuZdg6QbVwBhm0YYKODH5zTbbhVuH/LDcPZxpMN2dgZM=
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
