apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: factorio-admin-secret
  namespace: factorio-space
spec:
  encryptedData:
    game_password: AgAu0DRKa5P5bJP4Fxg4TTmENkGscj/CzNSBATuipKDLqvPAFb1i+eTYXJZj44IGQW0va9jnNzdTQ8o/zIOuOLJiif05zQPq1SYPmlh0lf/osexxwrk1swmXaI7hwS5r8NjrhLPrf5M0AwNyKCT0pbdj0pRl3qbWVwig/6AIqoC47II244k6IVWAAWykxVOMO3z5u8RbUvP+NKd1H/Ye59m8PT3lXewkVrL+QLCpKSrpJvbsmaCliQunppMdQo49JlaLsFq1l0sYR33GPAjAoGCLqpUrCUQtrPXYccTkCZCZiCKm0dhXrMtoLa4WmrI1yqDiedZJMR0dYzp68zreVd81kRGetmbMuMuRO4cYjEptKzvWsW8vzzP06kVBw6ypvKRJmFsi/pxJyjUN+Hga0XmppTUY5Xf4dx2e5GUViRj7gkYpeWX4esNHqdj10UTH64ZGGdAOMg2JLfmNYbxWYh+PX3cVl/pTgpr0P0GFZwy80+sot4Hyj9R7/RwkljNdzBTC8f9vsFsB6At7JujjwD/GCaIWhyUAoj0RLxchlL425s/K0qyCpXyV1pX8P/U+THPyaJMugRP8R5RE1vlhqSvfhGRx1U9N4dMgxJ1DbiTc/CMAVSsvYhwu2G5Dz/+B2iot5pM+6IIDwx/DY8fvKS3TrT5xThtJz2vYWpIuhIt8Uc0j8wOr+vQ0L7XG+P1c4PFILbRxQiP3kzlDzYcYxFQz
    rconpw: AgCkQ36Pq1vK9RTUnT8Ho7gLgsO7WjckS62shQqM6ZzW8W/gNGVF/DINPITESKhYsdCF9cMvrUNzBCClW1qTVxbVC+1l+kejzYyyZr1wuNilFgrkUVfL+2s5wopT3CCm8RDzi1tb3wtmxICD1wsvpZr1i2prlThH+CyL1KmVV/uX278tdrUCCbKSQBuQsgVvavppSSkikSRHAv97ihMMcYj7eHKM8NheeU1Vyw8R48G4abHfCAL2KfVPMsXYAfTx1bd6BPNp1RzhMeoMR9LrhjOHa4bOeXpik8nJ4B5ci5sBCW4lmASE6f2/hYHH8z3qAMTuBFtfCqIhY4RqjBdwKmDM1I/nyhzqQsEZoywXB4AEZNZdNDK2jeglR7/eOo/2oSrhr3LTKigQ/rpC4CljJ1fiUCAL/gUa81UP/0y+u1ye2/6bvAbpnB9QXBZhGCOiuTCifJZp1e0Elq3orQLt0aJwgnFWSTYx6gp9Kud6R6VyX4aWrW6HV6yxanOD7rRwoSmOqapB4olmaK1ptL1anmnTYiF3gP4iE1BJTHmFF+ihN9YZQYb2NfPMoqI7gs+USSG85wY9CdvZLwbnK4n6EuoXBDAKdKZrn5D1LZyBBCBHwCKcK+NoYakZQSj9r/kHAzN+jj8nGWac8Ogx42rIoh9MG694UEd8qIpyptobOXF9MHP7i0o/Zihrfi+uWZSC88eb7Eq3socOQBFlsA0+TqZ5
  template:
    metadata:
      creationTimestamp: null
      name: factorio-admin-secret
      namespace: factorio-space
    type: Opaque

