apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
# app.kubernetes.io/part-of: infrastructure
# app.kubernetes.io/name: loadbalancer
# app.kubernetes.io/component: ingress-nginx
# app.kubernetes.io/instance: ingress-nginx

# find how to use one load balancer accross multiple services
# resources:
#   - ingress.yaml

helmCharts:
  - name: harbor
    version: 19.5.0
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    namespace: harbor
    releaseName: support
