apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
  - acme-issuer-non-prod.yaml

helmCharts:
  - name: cert-manager
    version: 1.12.1
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    namespace: cert-manager
    releaseName: support
# patches:
#   - target:
#       kind: Deployment
#       name: support-cert-manager-controller
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/image
#         value: docker.io/bitnami/cert-manager:1.11.0
