apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    version: 0.8.12
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
    namespace: cert-manager
    releaseName: cert-mgr
