apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml

helmCharts:
  - name: cert-manager
    version: 1.11.0
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    namespace: cert-manager
    # releaseName: cert-mgr
