apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmChartInflationGenerator:
  - chartName: vault
    chartRepoUrl: https://helm.releases.hashicorp.com
    chartVersion: 0.22.1
    releaseName: vault
    releaseNamespace: vault
    # override with these custom values
    values: values.yaml
