apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secrets

# resources:
#   - kubeseal-controller.yaml

helmCharts:
- name: sealed-secrets
  version: 2.7.2
  repo: https://bitnami-labs.github.io/sealed-secrets/
  # valuesFile: values.yaml
  namespace: secrets
  releaseName: sealed-secrets
