apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-pasword: AgA3tCz24+m0gAAFTxM64DeNyDPdKdyRj6K7tCphCUt9QEH/CZrPt7RBLA8BoVNTX+nSAW3NciqYZR1uvDzsJ2O5ZhyPCSoIYApE0rapgbijxlneLPT8U/D4xiO448sOzo9f+4jU/vvNxEly65ScuwAljdtGC+16bSiYP8k0ZBBe6+EUedLZjBbVKhxA4MvIjb4iwyBeIz9yCJw71YBXTkyNyHSm+WKYb9hVjl6TzgoVic6tQ72ISHuKJu+biur5oBmg9KraCNeT6H/TQupuwI6RBORy+bfkjMJJ4n3f1U0vZL5aaFDeWZRT74eDXRPazwgKAE11heoILsFXUATpDG4xKy0yOvzJF/IsCc1LqFpixEep4g2m642IYGrPv8V000b1qn+EqVYGoHBqMEF3V2b5KQNlk/YmDHykG/340muzLjHGHJanEOgbElGkgbMBVKmh3R3VGJwyMV8+QSIcl56akZUvkXNgLfvRtnD90GQHmhlFpCjh2cd0ahG4B4wvwJCC1uWTvzsgvlG3eOuUKtpQuZ3hJgEc7WZDPMCjpbFs/Bv4EoFZyhXFvcOeNWDxL95zAatbrVh4YGJZCzMkMvs9Dyr7D3VC14rdSUptAZAD3n//6AAhNl7Y3hUm8iZZj8RBjMyqY3predGsby4DVZCSFg+MCUg3GotUjiTgpHQ37QWu1C7EHn1ZJsUXgJ2RezHRPtBAkvLM8uNf/tSFR6ZWcyMLSZYzEGe+E218ieyaHqBdWXJ5QV3UsHXh65NVigwVzpsTcnw=
    nextcloud-username: AgCOWgkbzqIjOc6JaI3wdpQPYkFFPvFzzvFxbPNyunnDnkxvt5LVcYuOccuNvwq+oVa/xBQAiL0CvGt6vM6iyLMtRndhNrkBvQAl3HAP2I7bLBY7WCD2yCDMbdG312tg0OOL96UYus/O9zHV4R8gmg53suQa3eZMr21BZDwxAGG4V6b6yMT5E2QRyNJ1ZMQFTWtzezivVNGToTmi9/xR92/tLncSoMwthBCpCNecJYESAxFYfZ82KSAInXD4OdMe0d0cXPhlTUVZX/81TSWA7AvE6ve59ytf88rsEjmohheOQ4jIGG2zhGdC31LBvUSh/irQBh6R4KFx1T/cAT93WT8ycZgxb0Lo+K7SAkN6AATqcqwBgrNcnb55XQqahDgPknYbx8vWFYBfKVGuh/TZ3nLxWG3ggUhkYFMSHTcTUVkF07BNolrHebvxzV0tJ/0IDV4ciGEiuz+qYmVyH489Zltq+30wapz5AKDlmoEy3fdgCZdv8SgJ3o+biJPa/qgOe0Im6Iq7w4e7HoOI8geHRawqNbYp7F6mfC+Y8DldPLrygOsYwj+eGEItKLTZQNS/prbqPieUCR3h1b3GNu5CHPI2tGwOnvQmGficEu+RHINsUI+kV4cyK5FjkQg4VYZXLi0cqwGjkvl3rMRhqZSA6OUQj07ck2syx0C15Z8U5U2cbLTHKXrEdWpwxp0shEjM2GiZAWmYPg==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud

