apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgBacMca9qRtJAS5eyKIM3CTEEhm9Jp2/n9q5Awyta/7Oq9MkbXaKct9+wPeCddf/+hj+VV1iLtCODsx1I/SO1FtwW9S4xCZpD6iheKySPJXP/Gh1qkyM0ZbvLVImziwdE6GJ4zGDsW5FGJI6/OSuQWsgNpq/fjEnzPGOmMERK5VTBBBbY4GEyzZl5kxnuviP51Jgw5uCiCrp7VXwWU2VvWbi/6vV1rbxWdU5+nr8G30eLmDuByI5bPjvmWsixae9o62uYCvqonTZBpplvRvQOahbv4meqChvoPZIhjEjhr2f5ORLnn+V9rqt1SDzDY9KQ+nrinCNoOgjvnXfYvsmJvaaDUN9zvh7qFQrsHdPbFDrDpYgHw7DAPgHqYWoa6ZMvt6Xha5QeYZVvSaoBHCcZZU3UQibGI20AO6/FO1LQqORl4OznXdKW4FXCwL5XIb0kja/CIKZvaywJ1zT3tMJ2X8rmcJkWVOE4puKMwLdqTTD/lSob8tcBmaAejDjkhPeq+/bETU5aiBpGX0chBO3qDWbSi3al+AdPX2um86QJObmbpnQdt1/0HZaRtUPY5Nybvebo+5t6zDddccRYlN4mVBWiNg3+sRv7bnIjDGiXMmrtmk6T1xlbB5OslZVi0Z5FIDdSFbZP+sVPJT55i0lYOGEp6kf20/lxPFW9A+xOpqUa31zEkN3e5bElPUpvOYy66HXDIvCG/UkTUnJ7pg4TMETy8csaKY6hj91DIgS11kKT8Ejor5GTuhv2Rx80Xh7yegvRk1CTpK
    nextcloud-username: AgDLuG6pWrDRvzKjGWG61QZqeMQumPRvBDP7Jaogctnk5FuqF1ed15EMratzcgRwgNi2LnwJ8LAdXIGYPE3rNSkBbNUohAumszB4I9X4kIR9mxBqpLmUuFi4tx5cK08ZPCXnTz5Wg0OkjsWC+Mwn6VBxtON/AzFP0nbgUb+EWW0r+mkgWzoGwggdvZ+FO6Z5xNdYapUxPDAx0dDudq+BkRex36vyzE6Tt6qB/fnOvzVaF02m61iPrpW/64BoywzzYcm5riO5+/padYEX7UsFb44gvKcazsWUzZLZ2tPTgf8IU4wphiQg42PPeJ3926fC4MjPAhLsdvYjpt/q9HI/NpCJjh+AgtmzADoQDALOCAQWLY5CvxSFADtRkoBqeifLPX0SIJ6M2NWk/N7GxOOdq4lZhF4PzKKj4nGVo8KICgLrT/y26DuhQW779OXOToDxqpreMrHOncNULSLu9yfh0rDoeQoqySYQNUuYJdx8+4pGrrwnYP1Z1WSX+Z0NnzxveEgpHvh/flauSOM/n21l40fZ4fA31alxMZ/5qX5QXQkEV45ZXzGYba2fOM1MquPkc/CINCEsrKp7esK99iH4lpeCb2DkCppMEApkDo4cJg67I92eHmfazENwGxDPuxvrT87q6jt1l/xCcKl7lZSlSLBaryFXLgIURT3eGRcRc7lUdU0IhDEbTepx9cVyntO3hMnsAnmaj1s=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque

