---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgBdiy7TD1mqgaqliI5QPajgkIA92SwkKgEao/cq5bndskK24WGEi+0LWyWL6BejvCPB6OSRnkNqgKwk9pltkf2zRDtUxLzCJI6qjvMv7QWczJTVLqFzs+Oo3nB70glfadmpGM7wLnp6iC7o9XwGo0J4X0V5oUBH+BNFLbAnNB30phbjWXUGcXdixXJuNP01upB8H5TTQXapNYQ7rzU7i3LQ7v3QB1So+p+GaDgnLwd7ouKwIqIzj2c2BeKPKAPbMy+xxY0TLNbkZ4FEN5TZVZHTg2RfYuevNATxEhON1JRmt82st6c+zo7Cjj5YaDUrwSVJu+LtsqcYLf/V/X0BJhiEQGSye4OvZEzMt52SRZJNuPOyTf2QUrKphXMwz0bJ/QmqEXMVC/eGF8lTzXSNNCVfQjazePp2oROxzohjeeF7ycvLR5eEPDCw+qndw/OdPZnsBPf12MR9TCjpZTpWlyPomzfdbL36oYFv5tTM+s/vHuFosPX1Si5aQMb/OXSh7C0pmPgtDjGCCghZ1WWjmSTjU7ST6a0cz2Ul+pGE1oMCp7CokNuWYb/qMGD4pY/+oLBTdWc6t8WZg7G5Ke/Jv8t9c8C/hG+6+XBpUxwQCazHf443SXia0Z8Agv8IKmlSk31/qyM65iMXU0WQMi9cu7ei8Q+OY2GAaOS6Kj33IIZ9c5O8ej1wcJIUnxo2gzdfn7+onrvtPo/tx3vsprIJa6iJqNJy4IhjCDia/5mLD2Y/wl+ZweXysTKxITY4NpWx3Uw1/TSC8PbM
    nextcloud-username: AgApT2nzCrky0mYOihABTeMhucieVX9RgxlNozA777VZUv3s2cWakaz0VJAOtOZs3Hr02DWCefeJoUtb6n2PPzRXO/pwSSbFAZtgzD2qxA3ag8XokzukGNfkfwIZhpOkoLe/Vnff5woQ2vTiNVHISsnEk1KXeYUMzQe0oFZUoqxjSW+ghyuhRar9TqXrWH7LyX0jVJQ5to46XxMo8n3CGStwhTx5PZTHoFigOMMiqZPu+/CaukLAcxCTHDVZHlA7WrEQMpiZ0suwC7Y8GREs2tMRopgy7ulMN5Ildk6feO0wQ1/HkGCY8U0x2i9LQOSPjdfTKzBMWkzh0YDYn+y1lzNBxV/paK81+1cEYQn7lp0mKEIgxp30WMV9kMKNCzgUt4RSM15Y78EUrQGPxls/nUaOFNVnwW39MqzLnXKRPDg+izSaEbUOymPUn2iGa7RQ1Xustpw8Hq9V8086Rdw6BzB+y+Zj5YwpGfjosSWonU6uc99OorBNgnfoFvkhTd/8ShwbgmGn3IGhR1/cMRNgpVa6bSt902Y9JN92AEDRJrYod/sGhfLCOzXd45vZ/UTwOjpfRDYCBCrzCSIK9IW4MHVE7s4ZsvJUqugbvdFcr+gq/Kz+oHFqo2MQjo6+IFoKJxUZWAKbdMt6BCnjDDDpfPfCt4mSzCYZxMKH+g5i2W87ZfkppixdQXd8pzPh0vMJYuEAY5NyVho=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
