apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgADgHzCwMK2gbVK1v4GUTnktafAWJqE0ROYdBraLYQt3r8Yw1JR31ClSHoTluXRWvTVhTG586bQxyRNIsQtEMFhfZ+0hEPBiltMM8hr/MOaEOb9Qouzce6V5A522L3BAsfvIVCdY7rB9Wy74t0MWl227aX7372KCvLM3rs2YSQ4JvyA6CcVKjMmOFjFF5bk0B9I5ZKCSPapLWMKnvv78tVluRMFnRCKv9yWewxRsg2U8BHqhQnLFP9AXVUdkw4T9Gsu2qr5PNlwZY1wH8CnVPZJKuFLjCQgxO8pYXaumKikHgv6gdQN012ZSS53sEvuLamp71/vKHhKcUBuQS5lI6fBsnuFPHrYlwVwi2oMXJAbDGE8A/uskEOBd7AG5IsHNdyLA9LSgu0mZutA7P1csvBuXAFGrls01+6VwEIFk0oS4nJi7t3o3OxV1MV1Pe8YWIllcPRkm8X44gbprR7ywoOHMxX3lE+G1YVBqHuwQ1IFOLeYfUaIgOpwKF1Md60FBX07V2oBt1n9Mf0M/Tr05Tqvxshz6wMcSW7rHKOkUP50H1UGXFXbOFVUa400vzu8gUeim+bs3eNsSuXIQHZajWCZLl24KZRixOukv6UQcoMfNhTY1Zd5pMgML8R2qhMAk9+9yBa5ygiAdz348jZSCdG3wzNU/HOfjHzRrvyA7sYIl9nqL+k2qjujK4XyzDuwoVlA98/MmnaVHbc3bjjurqI8NB06Rjm6U/u5RViP8sRNQOmLnOc0utY73ELBTkfG2nQCNk2TjLU=
    nextcloud-username: AgCRTezKbUmfZRcaORAOD5s5wTVL4C6q6siA2ZGlVYa9Bqmr8NWdJFMrzK8GUUgkkSYGAzHLT9eIukKp85uGkHnHwAvGVHT0OQa+OEYEdnwj59VMBZvKy5kCTOPH+RRkdiHnA7+ZzdLmT4EH8RsYFeO/sUBOpF4LsgCntqJJp4KPf6+0eK9yJJ37DeX4yzh3QVgz7DtPMEJ3HLIZijfaQBDxgLewn3PED+5fQMCtQa129dx3jL45tbT0XxA3DeWca+IKbNnPWsy7uDR0KsIiaVuFXRmPB4EXC/MEVIHi17GCjk/s7qDNW1UH+ARSx8pZyZziLssaFL+FE/00HtGfO+xi9jwSkEh/5BYu1Ksz9cphYkFDIc/YDsAVc/E0UcJwxA0eyXMjhHH9xOVcYst1hQrJPaM2l5Q9mKHNC8WhtPuXxCEWjNomG6xunjHpen3+6Fq5UfCbVlOS9bxdrSgUE0RJ/6u+IDp1OVnyBZ+3rXFUB94YjKEqB7EC1AGJ2yVMstX7Xr36lqyaJART4KKANyVmobFRf2WG8Tbo4hL3eiCqVn5n+1Yymi43Kws6yMXHv1SsCR2aD0NtUcSmZ/DMNYiAocrCNYNOrhj5m1ZlV/AxeTVyRcIs6vzyv2R5MD/rJQDIK7aKLMbfCbHgnCnrI8IMMwiEa7+le2B1myXjpL/hrKkWepPQ5ZxPXwM0yptQWsa0RbvYeg==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud

