apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgATS2OcJfQ5edfhl0SFdeJOhJtByd2n0H5xpI/e8PzIp3ij44mWBwmb8U130PEcwyi/SM8UYzx36S/1KUxmSXvIHDYM4v4QbftmC73KeLu4d+3HP09nOtAcmC6INKIQeJuIStN6tm1ArYlf2zrihJ8sWYN7+4aIvluyc+ZPTkwYCn3iJkYsVsLwD0Mhz7w2bBCLvlIcfS+WVZzZCk7eamVv6ekkqxJ/SIlC1c2/1h1oXkHY2brU0aBgGDAvPFk47rW/iXgjqryT18SHC8aGEKQ1hubhTHFghi7biPc/WXJoZNIQpJb051odUfhb8/fhNrl+1/pNs+nTNxaG/+8DnF8ncBw2IpRBTTn+SW8O5tR07LdvjeVuLesLHudMF6HTdSzzSMQ0dHRIdAiUGcMXhnX7L9qkGN79Wwg53I+nfy56U256LN2xVxnjTbG34hZrqfq4JIIaVYxXeYS2jtWkrENPnHFwKgj80HwS2utj7Npg49ktVlJxd6DolpB3ZVWq/akYTzH/J5PL/vqcM3WAADVQbzG7iQX0NhQnKeQbqb77YjMbULfTBlKRO/KkybA9I6orP2UAfLjJ8IUBK4AebymiNUd65yWdALJ6yURe/kYBztrmNTlfLj8BB+Js5PZ263/HOMaeFoO13lSegDWd5KRKdlKxeALyENOAMFrXQtwnC8qujPqL70Y8twRvmL94NAFL/TdWtFffGlscDdM+KVLMCT39kp6o4clNGyuLO6k9gMTwmmXbiMRxxTh8A9rVxcHM2/MaGLqS
    nextcloud-username: AgCjNU5vP6RO/MAp8guR1+9sq/Zu2/DowBhSaZBOepvgW+vuwaecMNByWmpozbZpzFQwfu0aWVNgJ8q9hUYCNFfourNRbvHyTn7gYWXjnWVDeJ0kcndLsC5gBWSzuYWW+jNd9n9TLMmT3+4L8bwTSafw2RLXPrJPM98Vr1VoCzceI2W+w/Tcp+EjvRdwdT+7TkGgSqyIy4TJOLfMIgZcI+o5yXhY25S3nQQuBn/XHZzKQTYI3YDNmeUfb1c9Pwj33CRu4skxivL2KWpIAGyTIc/KF8eVmi9IkZ/Ywy0HzDazQ1cqNgD85/QeVV9m6ig9U8hc2CJXsQalbPQ/t0LVvoW/jO2rnCna8m8S5Sl8QvvLWlv+UIpSEwikcyVtZfx0FTssD+8qhOIYOfC2fldeawGVSKlOPJmw8GyoDnOymmBdq4HToGdre4YF/IS90ftzjbnf+2UcbTejIEDJXv3nCwK1txXYCS9gJNzvzLTpN24BAIAHvvadaraPF1Ku63bU36rQUWqcSvdnpfNcnjg+dQZOhVIwGgz9wvfEPg3Vn0FvzzZGEcLPqYjBBn2XB2UM+U0hfTEbA17lrPcMuAo5fZq6lnTyc45Y6uq/00DWq9ODryCkuMnV3GS4EsJGXi/fUPuEi72/Os23mj+gRkw6jD7qNtky5aKdK/pbwXPPv59joZMNpC0bN+fdidYJ5V6fv45krHAHjH0=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
