apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: uptimeKuma
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: charts/monitoring/uptime-kuma/overlays/non-prod
    repoURL: git@github.com:vanderscycles/infrastructure.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
