apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# kustomize.buildOptions is not present but this way we can add
patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
      version: v1
    patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: "--load-restrictor LoadRestrictionsNone --enable-helm"
  - target:
      kind: Service
      name: argocd-server
      namespace: argocd
      version: v1
    patch: |-
      - op: replace
        path: /spec/type
        value: "LoadBalancer"
  - target:
      kind: Deployment
      name: argocd-applicationset-controller
      namespace: argocd
      version: v1
    patch: |-
      - op: add
        path: /metadata/annotations/ad.datadoghq.com~1argocd-application-controller.checks
        value: |
          {
            "argocd": {
              "init_config": {},
              "instances": [
                {
                  "app_controller_endpoint": "http://%%host%%:8082/metrics"
                }
              ]
            }
          }
  - target:
      kind: Deployment
      name: argocd-server
      namespace: argocd
      version: v1
    patch: |-
      - op: add
        path: /metadata/annotations/ad.datadoghq.com~1argocd-server.checks
        value: |
          {
            "argocd": {
              "init_config": {},
              "instances": [
                {
                  "api_server_endpoint": "http://%%host%%:8083/metrics"
                }
              ]
            }
          }

  - target:
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
      version: v1
    patch: |-
      - op: add
        path: /metadata/annotations/ad.datadoghq.com~1argocd-repo-server.checks
        value: |
          {
            "argocd": {
              "init_config": {},
              "instances": [
                {
                  "repo_server_endpoint": "http://%%host%%:8084/metrics"
                }
              ]
            }
          }
