apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
# app.kubernetes.io/part-of: infrastructure
# app.kubernetes.io/name: loadbalancer
# app.kubernetes.io/component: ingress-nginx
# app.kubernetes.io/instance: ingress-nginx

# find how to use one load balancer accross multiple services
# resources:
#   - ingress.yaml
namespace: n8n

helmCharts:
  - name: n8n
    version: 0.23.1
    repo: oci://8gears.container-registry.com/library/n8n
    # valuesFile: values.yaml
    namespace: n8n
    releaseName: support
