apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - ./secrets

helmCharts:
- name: gitea
  version: 6.0.3
  repo: https://dl.gitea.io/charts 
  valuesFile: values.yaml
  namespace: gitea
  releaseName: git
