apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAQoR/T0lhfnpT4d95Tcj8DBqwggXymmheNZpabnRpN7axudAbqivrr1d/YjuMOz9qQ+j9J/xtJM6m1xanQ0cg6uL2fnByq2/vXmyIaJQCvLBeLOs1AM9AYopgGrSmIC6eY0746pxA5k349bUTqIIc1401NaB5p16ZTYYjskceoNnlk0DA7fI2XnnGSO6gjxBQRnFVgxVpYE4FdmtzwXL+Yy1c48NsnZVQyeDNfKnpnVkIqWvffpw/SpeBYQ9Z9cBMv3Pvol68oGPPWsK0+pLl6HOpOTFWKhOLAGodsB81O3/Li5QGgKeWXv8jq4Tx8xoxb86pUdFl9ECbBSDt8L95lo5LOgjb36eVzYMn/sYHCT7nbxzYODPqdn9KR+ZZT9b5u7R1ILqSNPyiD/p/GO1S2koNzmGvXeFOIWDQYrIfxesYl0fYG+DCkdYcH6K5fMp9PS3n8kfJ0CiJJrAsNbb+nyyphu2O8ql9Yt1hROhaGKp1WAON/37V4CKAsVYoXHm1WIbhA4hujqQMcehqIe9NYHPmAGQxoA+Bp/1jkDzT5VTknomzmpB+RgNpdlgEL1YEmXuPmDQ//mkQEgkdpmQWo1zEJsax+AJ2e+ty8ukTA0L/9AZG5dxVjMCal4Z8d43JUkFJSndtNL8mALFFov0oN/N8CdhW7HKkjlGNTTPmehFet9+NayfJ4gugShsUOtLNKmUml2tlGMyOnjWiGLwtq+OZP7U42yJziY1aG+2fHsscqXTNOJZYHMD7LarMyl8LYGqIM45LVpYSoxKAjYbdn
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

