---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgBXBwBAEiFx2IFDFuxPTj+UNZbTSRyVvj6uVo+nYP1+2XABARsT6TDfX+AKIWpgw1nzujfjtYcKkUJ+wc/gb3fKZTI55tCbqnNy2FULWg63hMEm6yGBLc0Y8UUtJUcVcuSWwymWTrkcK7+701Hug6uuUU5R7gvRKZTX6YF5d75Y462Un+vLqPdxNYgfCbDqxWu0sO8NQ9P7WB3KNXGaGXNKrCMrcT/j+ZcMODYF/9eXWrCu0VaYXgEK4PcePoUSUwaZ3X8knAYaQWFJaSi30/gbyqDauv+EvK/JZxqhyDxNbxZUd3bbvhZJgY4zAYoKE60kS07yIw29g69DyG3j7tE8+B59tuA+F0VrkII1BfF8hWltOr7XD+J3LQd6RsX8/NAHI+ZBuiqmYnXMtfvhHJlWuU3GHQYtVbT8SNMumcFy678xeYUHnYDdhVnVWDc/Ghh6NuTl+cPY8ctmyJfwGx1fxDBKVsgG3D5uyLUp5MRh0uVc2V4GUJ5rjXpsdfMi0GyGd5WC8D/ngKb3mvI8Bf0rGo5xQgFbdU2HO9A0XXcFkmwfjDbn8JVI8Ruhf/0KN0uI+ceD0QmmkfdYAUa+HCjrZFI6Qrk15feVPRuXYkzdBOzDrFYY2qFwMu4Cgx/BJtr4Pst4bquWmRDuYTm08GMiQcqSKT/ZCT0LlDASK8MuudktPyNG04A8l104LEwCaN3+E66PYaPz6XuafMMKbNwJIIDpguGuDaUjas5WGyuLJA7FlDPYtGyDa+5yyiMsMLTMelxvD4iPehTUTM3Q+9ftzw==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
