apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAD5WWoQt1eko12KSW/8xykmKKIq21gPnCgPHRyyy/aTki4QS4mTUrM9rLMAmolthlM0JwHqB0Gk82D1oBdTq1PFTPuwTtMGs+S7qO5zC4Bcnr8Ni1vn6VhlWK4fwsMMUqKziHTmO8VhFk5dQfw3cDZTw/Fb2vDZ/swjyApXBK0faCn8NZfzH3yIvMsFnKi6/wAMt+ynvUN3HFZIsOdpabYxgZZcNvf+plsNqSJc5Aafd2K74IVZOSLMxD4sKVfQaQXf5v0uUM2sgU6oKlB1Tqa5Km6WFtnzIsatjWVgJ6uFLPr6Q9WVYhCpN8u3BQX+qoiq9r+viJ/dIvRjRvPhILiEEkIu8SZyMWggRPOdwQhO88zxM7DtNTw4P18QKlWQ57DG4oaxOrpAkajbfFh8LJWpXtKoBK2rs7ovBdVyQp3CXPvBkyWIelKgEDZ4+eFS0x/Kadv/FHWB8i2GEdcc5UdIgvYfRaT9iBUHFsSGIdln+qjuMTNSG7J7u5Ep/KaQQ+K0eUWWgPWIYA1xfng2RQTwCV2QWpZfB3bZ6UfXevJmTxki5sAfe9UMdQmjbcb1TNdD6X8aVW/7ibmM7jnR8QaLygAy+aX8Otm/KdrfPecEvMvQUOFJD1FQWmYLYuHThc9u5Iqgyo78kXJTARZf5GXHzPPIMApucde+vNHigcj5y4Mpf7gOCt5/D5JEEdJjXWXp5GV0gPPZ0X3xME5tCj9Vv2pjrOp2gJGMw/uACOdmsia0MIs51B35o3o47Yj0dzPzMso+0eCB+5MfD814c6R
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

