apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgCG6qw0A7ZbHA7v4KMc5xsBRf54ys4byu2PF7B2UqyRuJFq3ZBmwkRjHr4Tx34PMQYWv5/DCdkJSuoe+g+pTW6KvoS4Pg6eIU+i5uOmQXNCXNZRSk17nGtimlmKQfdfPJ16yvFwewLEDWX1qY1yS42CpzhLEB/XP/XUGZ3DT+m53r3EFF34kowtU4QusluYzeFj+18WM+v5dko7l/WJNQ1w3k07YmGEcU3f8t07REHrsuRAPfJxzaTDLsHYv1d7az1hSXTz1YuuhCCkXEpgrQQHJcCX+jGOMT9tjxtAV4ypYoPpqLL97D8qJDgOy6gFp6K32gTCJJm1VyGwvUJZnNlaSmtxB8CLGoCz7d7x4jtEEd5ZicHJoKXrt7Uz+xZMBQkKuLNBGShN8agUHSgU08TFY6Q+9qJI+oM66A0uadNYMrI3oXodzvW/Qv3mlGGga3Wcf5X/vx/kCLMsHYGECqG85QolCcpe31WcAA2lmuwCKpdbOtoYGP+vKJF6BZ+MKHAdsxl2nVeHaFHF0IpuGakZqCCSfcrtkHbV4vwPCfXuPgGyX90eKpa4c3JPfLyjUhy0D29t9Ajw7QjEx5w53oPUK1b/3c43jR33K/VnQWCRDMNqxtMST4bV0yJfAZk4xlHd44S74E2oU451efL1fKxgtOw3FWjzGQEVobkLS+cLajn4+JYWFETRoixNjMKjqVdglrGPJbsEz+2BSdiYExLiLZO4Dr407aDzQ9+zugSnO+f0hnKf82ZrUNSKlvt4wU1UK3/iJTqh6kPu1FJRXpiC
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

