apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAp+1TuCf2zv0tuesgxZcSykE3QNmR2FdoCKX27Xac0G5P0xBluojuEdgZmRpm06Ktub057d2PW5a1b1exdylb8peAwY1rgCtaAldbF9GfDrfqaarhC+MtslHKf7GDIQQtgTRQDwMB76nLiCizUVIg62XpiXf02dyY5B5NU2sr5kaNULctZP+ZoT61B1f7lYmyhiZMNNgGCsP0Xwk5DE4fo+QrKVzuP9SG99nAHQ72r/VfN3c5sltobDWScakRVuqtkh4mj2WiJmDm+zDb70CvDxRIGSdWqR6yEHIg6cbs0Jm3ozMjhAUQ0vbTg99xCSupRJkddefeZ1jwcGUjdILxbLKMvBkWLXFbdnhYJAjuF0GsGpWM2kpSI2tF9ibaYq9RKQflmXa08qptr+l4xzLs50ST1VMo+FlG+hCNFwPC9o+ESIeUKGp5hDVUyl7gh6xbwpxig1zAtgrfn0DnB2c2ElHWHFA1I0VjTx5/LoxS6EP4QKJtz0rdzrK6TC7A60lZgphF/mCEEHXLf8DEY88N1CvWpeDtZ37qroYCXpEqzcwT+r+mKmHh5D4etLSy+fPR5UImyU8uZfOb0kBTDgG+cpEVPKY0Nk7wwPsRqPUAeoTQdibFTGjSZkoSyrsRDPt/JZi+CSFRS2TkRD54NgjyG100gDuLXTIwkg8Cq1BSolzg8+xi6i/hc3lDHXOSW4JXIsZTrRQhR1QEo7gtZ+YMSkrOoFHImfyUZoFMNsIapYDIrK9YbcbhBpCeWxuwdDdwRWUr3Vwoxcg6ByLn7m4iJtg==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
