annotations:
  artifacthub.io/changes: |
    - Change maintainer name to GitHub username
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: drone
      image: drone/drone:2.12.1
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Build List
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_list.png
    - title: Build Running
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_running.png
    - title: Build Success
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_success.png
    - title: Build Failure
      url: https://raw.githubusercontent.com/drone/brand/master/screenshots/screenshot_build_failure.png
apiVersion: v2
appVersion: 2.12.1
description: A Helm chart for Drone Server and Drone Kubernetes Runner
home: https://www.drone.io
icon: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-128.png
keywords:
- kubernetes
- drone
- drone.io
- droneci
- drone-ci
- CI
- CD
- continuous-delivery
- continuous-deployment
- continuous-integration
- code-pipeline
kubeVersion: '>=1.13.0-0'
maintainers:
- email: burak.ince@linux.org.tr
  name: burakince
  url: https://www.burakince.net
name: drone
sources:
- https://github.com/community-charts/helm-charts
- https://github.com/drone
type: application
version: 0.0.9
