apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-kustomize-options
  namespace: git
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
