# https://fabianlee.org/2022/04/18/kubernetes-kustomize-with-helm-charts/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: git

resources:
  - secrets/

helmChartInflationGenerator:
  - chartName: gitea
    chartRepoUrl: https://dl.gitea.io/charts/
    chartVersion: 6.0.1
    releaseName: gitea
    # override with these custom values
    values: values.yaml
