rcon:
  external: false

nodeSelector:
  # kubernetes.io/hostname: space-exploration # this makes it easier for firewall rules and makes sure things dont change

# making sure the game doesnt auto update on redeploy
# https://hub.docker.com/r/factoriotools/factorio/
image:
  tag: stable


persistence:
  enabled: true

factorioServer:
  save_name: "space-exploration"

#needed if playing online
admin_list: [ 'VanofHoogen' ] # put your admins based on factorio names
# - "john_doe"
# - "jane_doe"

white_list: [ ] # put the people you want to play with you based on factorio names
# - "john_doe"
# - "jane_doe"
#
service:
  type: NodePort
  port: 31497

  externalIPs:
   # - "172.105.1.131"

server_settings:
  name: helm-kubernetes-argocd-spaceX
  tags:
    - modded
  visibility:
    public: true
  require_user_verification: true

account:
  # Existing secret containing a valid factorio.com username and either a password or a token
  # Example:
  #
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: account-secret
  # data:
  #   username: <username in base64>
  #   password: <password in base64>
  #
  # accountSecret: account-secret
  accountSecret: ''
  # Your factorio.com login credentials. Required for games with visibility public
  username: 'VanofHoogen'
  password: ''
  # Authentication token. May be used instead of password above.
  token: ''

serverPassword:
  # password required to log into the factorio server
  game_password: 'bae'
  # Existing Secret containing a `game_password` data entry
  passwordSecret: ''

mods:
  enabled: true
  # in order to use the mods portal you will need to specify the username and token in the server_settings.
  # name is determined by the url, it will be the last part of the url, not the title of the mod.
  portal:
    - space-exploration
    - Squeak Through
    - LogisticTrainNetwork
  # unofficial section is meant to just allow you to download and place folders into the mods folder.
  # we will not check version compatibility automatically with these downloads.
  # you can encounter an error if the file names dont match what the mod is expecting for example
  #Error Util.cpp:83: Failed to load mod "Squeak-Through": Filename of mod
  # /factorio/mods/Squeak-Through.zip doesn't match the expected Squeak Through_1.8.2.zip (case sensitive!)
  unofficial:
    - url: "https://github.com/Suprcheese/Squeak-Through/archive/refs/tags/1.8.2.zip"
      name: "Squeak Through_1.8.2.zip"
