apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmChartInflationGenerator:
  - chartName: consul
    chartRepoUrl: https://helm.releases.hashicorp.com
    chartVersion: 1.0.0-beta5
    releaseName: consul
    # override with these custom values
    values: values.yaml
