apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: octoprint
  app.kubernetes.io/component: raspberry-pi
  app.kubernetes.io/instance: octoprint
  app.kubernetes.io/part-of: infrastructure

labels:
  - pairs:
      app.kubernetes.io/component: octoprint
    includeTemplates: true

namespace: octoprint

resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./role.yaml
  - ./rolebinding.yaml
  - ./serviceaccount.yaml
  - ./persistentvolumeclaim.yaml

# helmCharts:
#  - name: octoprint
#    version: 0.1.1
#    repo: https://halkeye.github.io/helm-charts/
#    valuesFile: values.yaml
#    namespace: octoprint
