apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: drone-rpc-secret
  namespace: {{ .Release.Namespace }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace "drone-rpc-secret" }}
data:
  {{- if $previous }}
  DRONE_RPC_SECRET: {{ $previous.data.DRONE_RPC_SECRET }}
  {{- else }}
  DRONE_RPC_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}