{{- if .Values.kubeRunner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drone.runnerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drone.runnerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubeRunner.replicaCount }}
  selector:
    matchLabels:
      {{- include "drone.runnerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kubeRunner.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drone.runnerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drone.runnerServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kubeRunner.podSecurityContext | nindent 8 }}
      containers:
        - name: drone-server
          securityContext:
            {{- toYaml .Values.kubeRunner.securityContext | nindent 12 }}
          image: "{{ .Values.kubeRunner.image.repository }}:{{ .Values.kubeRunner.image.tag }}"
          imagePullPolicy: {{ .Values.kubeRunner.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: drone-rpc-secret
            - secretRef:
                name: drone-server-secrets
          {{- range .Values.kubeRunner.extraSecretNamesForEnvFrom }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          env:
            - name: DRONE_RPC_HOST
              value: {{ include "drone.serverFullname" . }}
          {{- range $envKey, $envVal := .Values.kubeRunner.env }}
            - name: {{ $envKey | upper }}
              value: {{ $envVal | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.kubeRunner.resources | nindent 12 }}
          {{- with .Values.kubeRunner.extraVolumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.kubeRunner.extraVolumes }}
      volumes:
        {{ toYaml .Values.kubeRunner.extraVolumes | nindent 8}}
      {{- end }}
      {{- with .Values.kubeRunner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeRunner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeRunner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}