{{- if .Values.kubeRunner.enabled }}
{{- range .Values.kubeRunner.rbac.buildNamespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drone.runnerFullname" $ }}
  namespace: {{ . | quote }}
  labels:
    {{- include "drone.runnerLabels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "drone.runnerServiceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "drone.runnerFullname" $ }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}