{{- if .Values.kubeRunner.enabled }}
{{- range .Values.kubeRunner.rbac.buildNamespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drone.runnerFullname" $ }}
  namespace: {{ . | quote }}
  labels:
    {{- include "drone.runnerLabels" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - create
      - delete
      - list
      - watch
      - update
{{- end }}
{{- end }}