apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: drone-server-secrets
  namespace: {{ .Release.Namespace }}
data:
{{- range $envKey, $envVal := .Values.server.secrets }}
  {{ $envKey | upper }}: {{ $envVal | b64enc | quote }}
{{- end }}