apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datadog

resources:
# - certificate.yaml

commonLabels:
  app.kubernetes.io/name: datadog
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/instance: datadog
  app.kubernetes.io/part-of: infrastructure

# labels:
#   - pairs:
#       app.kubernetes.io/component: uptime-kuma
#     includeTemplates: true

helmCharts:
  - name: datadog
    version: 3.49.9
    repo: https://helm.datadoghq.com
    valuesFile: values.yaml
    namespace: datadog
    releaseName: monitoring
