rcon:
  external: false
  # passwordSecret: 'factorio-admin-secret'

resources:
  requests:
    cpu: 250m

nodeSelector:
  # kubernetes.io/hostname: space-exploration # this makes it easier for firewall rules and makes sure things dont change

# making sure the game doesnt auto update on redeploy
# https://hub.docker.com/r/factoriotools/factorio/
image:
  tag: stable


persistence:
  enabled: true

factorioServer:
  save_name: "vanilla"

#needed if playing online
admin_list: [ 'VanofHoogen' ] # put your admins based on factorio names
# - "john_doe"
# - "jane_doe"

ban_list: [ ]

white_list: [ ] # put the people you want to play with you based on factorio names
# - "john_doe"
# - "jane_doe"

service:
  type: NodePort
  port: 31498

  # externalIPs:
  #  - "172.105.1.131"

server_settings:
  autosave_only_on_server: false
  name: '[BETA] helm-kubernetes-argocd-vanilla'
  name: '[BETA] helm-kubernetes-argocd-vanilla-test'
  description: 'unstable and experimental deployment method by me. Use at own risk and expect loss of data'
  tags:
    - vanilla
    - helm
    - experimental
  visibility:
    public: true
  require_user_verification: true

account:
  # Existing secret containing a valid factorio.com username and either a password or a token
  # Example:
  #
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: account-secret
  # data:
  #   username: <username in base64>
  #   password: <password in base64>
  #
  # accountSecret: account-secret
  # accountSecret: ''
  # Your factorio.com login credentials. Required for games with visibility public
  username: 'VanofHoogen'
  # password: ''
  # Authentication token. May be used instead of password above.
  token: '97154b15a07fab9394cf9e0a064a1f'

serverPassword:
  # password required to log into the factorio server
  game_password: 'test'
  # Existing Secret containing a `game_password` data entry
  passwordSecret: 'factorio-admin-secret'

mods:
  enabled: false
