apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgBQF825UXGFtcanbI1WHbcsWzde8OfgQa8VIWWw1YmjbIMEJQkKmHeafhBdxNU6SspwOAoldpMTohSbvNdWYdtE3w+hF5QgDxEOg38mx8uxam/uAQFJr0ledT3/sUBMEMiTdSnX/HQJBJZiLm5UkpQXJ8Fy2SxWlmZXWCVH4to7AZ64le7VoRA5HCoPhHv32WlKMCNljwaIuLSk8Um4EydMVYYsu++T3O3O/aRfz4qyu4nDyzjTzIMVGNn+8b88D8trHFPEIvfcfGRUfBzXn0BD9R8JwijlRQT0w+QBiVvfBPevDcJuP3oNY15wIzdrHeeqHlCnvkJeM0EiZy/wGXGQizqRWnXxp/kQ+rU4WyklK+wG3hN7Qa68suvLkNCdYLN4GzgUOAUD4UBEIxvE1ZkOlC2w/Aq07AKonLiTjbUWQOlnbhcRzIkhiSXeLfHy7nuOX0181obCb4GpL4f9H1O3V+3ZwuDj3HItyjRuBX9wSGlqwC6X+mFQV687928XB8PoZW78FIMafJ03bwiRPhIxO5zivIV/4BFD/F0LUl1G9s5kC66BJhcrWa/E+P6xA8S/mLCD5TQ+3dxA79LUWjqeCGpxuBQ/q7yacvT5nvGD9XB+bEa50NaLDbJdu9akubiFwQbG4YlOBpzQ6bq1ZAQO6bTeoA5P4bDjWeDdIKwdq1FqsJe3fK6wPEFQGEwuvJf1Y47MBGFb+eREon/M9s8YGRAlEERMFhU/HAzZ/E50HVmSuALNsZkFEU/kCMGfUkGbQBnbPLOpjzaZsIreCMdx
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

