apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    game_password: AgCY8a6fqn4tuwZV6ZgULdt0fV6RZZb0PQIpknQWXi/664H+93QmkxSovbJ9RZqS0B3sCFqwDy2cnXO13tnjPakWEwu1NJSoH4/7GasSfqbcLpaUwkAlYEzqTTRLAoOE59i8qGsTvku/HZKETgpbuM/COiwv+p+CfNKBBz6p6ix89deZg+pRKBwV6wuBBXtPbLF3QzDC74XAQGPHGJWwRdqDLntuC3xp7sbU2aEYJ7F8x9IiOi2wPP5C22A7oa31Z7AhV27i3m7G0DVDFOfsQ+mEjn5xxK3OHRNpWKS/pA/4jZNN81OOk5Ev7FfqXMMZtdmc3LKTKKYZsb7OSSKY/skVVWWNbxqKtjobjTJni5mG1EOSIH6EDNvljWHdwtHQZlJ76jnYVR5MutfQYcJNLG92zkPqCPXNkLWF5S36MIwx1TH4PCadZZsUSAYekKWfX1QsotoKnzdfwiFU5Z/EObtVjUU6pWUcAEhsBZ0EHqHDIgt6WzXPVu5G3SWU9rCnQ85ouG0KE/imBj6E1T5uvopg3VC7fMLQS8HkvkBlUWwnpGPp+MyZ6333yLwbZaBREmpTR9EwUx73gKwShzy2LfkCqaYwVvrfN83i8LKKzMTf5Sc1DPruwq7KYq2zx57og6XsX9ArtzlvPpe01Jc4ZQ7K66vEq6rz67QDtQ1jvDEEVATgO6rmKRXzelGWhmRSh6xP6rgzAF3h6YxkhknhHxj1Zr3ZSKi/mIqhB3u7mXJBpqA6vqXz3XNoUzM4uLbBWP+qiqLMiVkJeNDPO/wDxFAp8A==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
    type: Opaque
