apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgByovO8PyBMLenTV4QuMef7L8oOor561BvvMwJ/nqpVa3nHwVYJbJOdundtcJLYrxZrOMycshQmx9giWA79U/ZIqY7+qPRyxY6mT7hhA3i4kIckzbeg7E7PY0a0CVVSEkCeiUs6fww3ccYpTBpKAcbQ5mTfmU8z08SJbB5qmviUBRxNkh+uA+q7o0ApLSOFKfWDL9XvaUlqW+vRmTfi5gq4MICO2TWfy2j3upb2CQS2kaY6JPNHpIKR4/I9HsgewZ1LVTgcuuBds4QSK4UOzjxvWiDTvaMyNoHgmDBj6FZhPw4X1gUfu60ODvWhamGdQvncQ6Tp2rMp7OmhrsI50nKXeARQpXI/ia/TDCt1sO8cTNrgH24M1LxcYmKxwfCn04qHiCMVUU9X/uakrc7g+ZVPSTnLwoljO9eR5lHu33APKp2Bo38I8AWvxSveUP2R2eWXhbgJZkTODXI/m0Uc/lHqv6g+WqY4uPAjLTPemfuFwKD7kqSnLlSpg8FJcoJwh1DHKsOVWkjYDhj+a1/VKm3LOnJBHowu9jrwxv5WSh4vAuDQHKnYcfQoIerBqjnwof0i8sQEdmM+TAL5w1ul5fX/pdXyfqXDwlyaeZ05OoEfUfAx9jxghDFoGEOwVHdjO/tBI9pS9/+q4yPq2ieWta2lQS/ExuOOhflpZPc5ROfoPnUDs8QR/0Mtj0XbRctfvcNOGunWLFPBzO6X4V5Qz1rlzi1HSvpjbJC1vhoy8FP0oG+GxNvYve7ENuqdgHOu9dqVklUS1SL6ZgoifILzOCg1
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

