---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgB6NC7RGlJ1ldQCBO/gJTeoujNeVT+NE+A/KjoqdtZVdn7Esv+iJq3MW+kUlLXLIyigDNZNOna0hb2CdljvCJAkqE90hqfYrgGAcnxRLiXUYozp3M2t4Fqq9CK+wsvANplFH37pXiRpwGTQdZIsNzl39as+JF/wj0aarbi0iL5dfsRuIvuO0/N/jdLdtB2545XpXgTfUZhRx+Z5xfSv50+AftUxVq4Vhnmw7BHJoxthYleOe8F4mBY4xAdaupxe/atIBx1y361HRneV1OTGibBDy7aXDhmi9tavOqw3oLfrUgHeJ4nb31yWWIOLjETsXF5lWd/wiGb7gkYiNJf3MEF6E9j+09PaBHKJdeIMDuVafGw+GVpXd3wWUN5K9J3q+ifDRcKDN/ySrW1XmhFV9PpyU0J440L83teWNzwyQyF5HCn6g6c7T1HzeANhEMI0EMupihEOobEgTqAfZY+6X+V7lmnlQMkUPg5HJ90u0r+SjfeTxiSH6+1Ea45tdDPwpK+4mCExlEkcuDX+t4Sj1ZsdRrFEyQulj9HnT6zj+lSA3/FFDdqHtjoedG/g2QIY6FDIMYdhN7BPoShsdQQcAWODLf9oxkRFjMmW6l7FQJ/QEK8libp9/BkqOsrQAoBlwoFjeTijIH7bveQaLqRop22q9EG3F4OwBTd2ofhFaQY/jywmfvgkmbiHksueWFhOxNrR/+mkI1wSRMKvnK+KPe6qKxxbhWTNgdIcKfdKAU6AZwMQT86cToQrp49sT1dVqhhy0DIvi33riePQXp+8RvTsDw==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
