apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAKSXL0/BbFBxMvnmJsOykJTNrhjSB72OFkgotQfFbkCEO/6BEL13tBAJ24SbjDxdxsn2eAXdz6m5ssUVdh8zTCd91unOFPPx7u8Iqqf7MEvHhIVaBRK4CB83GaTtYjQbv8OUzcMN53oh9XDzpaWnvbdr0PFnKaDJwEmqRRepacdjDKyzXhATfE8mu4qWAESl3MwbSj6lO90qvkZRCfLotZdn09xFYQhRePREpfXlniuYPkd+DcBvqZ4EGaXCrLw3ijJV3yiic916b37Uj7k+3Gi2lejWXVSWTOBrFvnNaVfvYZN0wlw3Ul+YLouCHGOYzUJNGsJ0Kx2HvOKMeP+7gWPy61KlyTXYkS1Ov7v6hNaNfnjNSsE6pvwstx/SzMxwplwdhn4dUfNjLZ8ap4W89Yr7Gw4xt5S3Jp7bVwoHGyI6L4F+Ahc2uovTEgWL6Xv7lva2lLQR60y8qg/oFMKR885zTyG+aq35nbXwHk2Nx/44Rwin+9rtApHGCWGsG+cDswKcInglzv9UpAqd/MEwyFFapbmQTM3eOJPrqcY3htOQrpZcjM4bgYpsJuQyO+VIvIX5aW/oMKl6dtw1gLd/tCifXYDaHOuDVpHb/Yjf7BrkpHVduUt/6wHCDwd4FJ+Vw4oQ7AV8M583fEDIZEuw8JvwRtifLUh20N1I9lHEPr/xwdC+5kD77X5+dOsz9u1AMXG80v1GjH5yKxTF0Otgmgka/EyYhVQUA8DFOI57NZUxBj4Q8j6FiTktbaxCoN42E0OUdeF+zADXS4l4a8M/rgGg==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
    type: Opaque

