apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgCQYijU54lYPyEbmdO+TQtGgUpjDtyatyF1451/cYXnTGo+F92PsYb/NF4/ooCWAHKkdrFF18poHxvHz4YFu6Xil8Xpg88odz/fQyRTt0C6/Ag2R6ld5qRcAjlOK7dX1sJ5Y7CSKcx+Z+5EFAjBBFpZqKEpEPGVgNM0aaGFsR8c7Y5J/MqHK0/fjBrvEmQ5ydNZExDxSOjMASCJQW0jmXvO+NU6SJXUlv+MTZWfiMlOgSh+0TeBRpzGnCzK/fZQ6mifTkSfLTxex483C5mun+QaVVUErByoKb9jUqwE3afZbZkZynTIUrLFlqi0ZOzV4JXo7cm2og8HGiMSPJJnTsVR38Hud5nRwggAK8V8W51FhAXU+zUVPguj1XNkcZnOOfINSlQIpuFur3FA7FY8c/DfnYoPMw9W/jjkcbw8vPyLTz4QmvFcknuhfoXEB+CRuqQB0xHFfzFz6o2OZhjA2wfplbaeCjclkE1abKVE5SU71tOo6f8CsQF/tYo5e3Xay2EwbuDHjXW75PYpBNrpr/BW6TqrTTuw1nvwyCo4+lhf3uBUtBcTElVUOVjjDwjUZYLiL2QMP0akk+O1LmZgJrbxwj66Gjq04W9gIKPfSjeqMFVfPclYYoMBpcVpCeKkmYy787bO+7Luvnt2kOOf/S9QCkhbJhcawilkgmrZTipl3DQ69E3d9iAO1Aen9UREm2JNLFPgpp9zUY0KDFWyjBlOJccoeLhP1dOVu+UA7GB1lblcxJssivVuUKiF9ojlR/79F+mm79nbMP1UAFo0mM5Eew==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns
