apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    linode_api_token: AgAsO2CZ7G8T/40BvSXXf8b1kDY6FE3JqKvnMO0AEoFPH0eyUeO2qBYqzZ55tqKh4f2JlC7COuDwL4UhDgfxzTW7Bv9nqXm3nlw3qDMWzBG8AEHxtKRh8P6Bdbf/0YK7M0RoV0Wc77nQn7w7aXHFukhf+D4w6Qp990+5rIDODQjzESIOzgwL3tM9ipY5zuaaSRvNJIBsF2wjOr7Ljs4hd4xnFIzFAxMtVUMOGWafi1JxYsw89JpOgLTVWT+knc7JTxlRBFxKX0wcG26FfDSXk+d4TBOCCWfye7MuNfv03IQHkYFNBixUcwiLbFhMs6b36avZ+6zeZsuS2QGiCUPeEYJU/BHptJMiEEDYY9PpRh4AOQoelj4noZ2+1lPcrWNINMOjNM6fBG1V3eKum/U4Sih9qW3HSwMYz88DMIKsVFezQaFabKHarn2BQ3mEBSo/N1fLn6XhkeGbO4SGqF/lnwsZ4BY4u+Mix8c1idh/RxcZYN/b2YKDMrQ3L3H2wHe4IJmZmKHG85nZxV9u8z/DUFQWKkMi4oPKiExA5QDgK2FsdY4c/TPpL3Flw6CsGOySKhTZDWRZ+/Iy9xELBYiOPqKOP2sLTLzdBXJ0MKVBmQ6ZV23ksYFUjlrJ/suTs2XqL5LXUHZMwqCRWbO0+MHOFkX7tD04HsKGWsYBXLLjNXTMy8KU8UXek2elPeUBCuNHgU9v3Pq0IwRya/0zT3BLx0yEnPxFkVGeii/lGViASkmFR7I6quufpVCn3Fqw/OCNrUGRSiz/Z75h0b/GBgMy58kc
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

