apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
# app.kubernetes.io/part-of: infrastructure
# app.kubernetes.io/name: loadbalancer
# app.kubernetes.io/component: ingress-nginx
# app.kubernetes.io/instance: ingress-nginx

# find how to use one load balancer accross multiple services
# resources:
#   - ingress.yaml

helmCharts:
  - name: keel
    version: 1.0.3
    repo: https://charts.keel.sh
    valuesFile: values.yaml
    namespace: keel
    releaseName: support
