apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  # kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
  - target:
      version: v1
      kind: Service
      name: argocd-server
      namespace: argocd
      patch: |-
        - op: replace
          path: /spec/type
          value: LoadBalancer

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: "--enable-helm"
