apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime-kuma

resources:
  - ../../base

# For easy ns replacement
patches:
  - target:
      kind: Namespace
      name: uptime-kuma
    patch: |-
      - op: replace
        path: /metadata/name
        value: uptime-kuma
