apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# patches:
#   - target:
#       kind: Application
#       name: .*
#     patch: |-
#       - op: replace
#         path: /spec/source/targetRevision
#         value: dev
