apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    version: 19.3.3
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values.yaml
    namespace: prometheus
    releaseName: monitoring
