- hosts: all
  collections:
    - devsec.hardening
  vars_files:
    - secrets/linode.yaml
  tasks:
    # use a package conditional
    - name: Install prerequisites Debian
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      with_items:
        - sshpass=^1.09
        - jq=^1.6-2.1
        - gnupg2=^2.2.27 # dependency for docker
      when: ansible_facts['os_family'] == "Debian"
      tags: prerequisites

    - name: Install prerequisites Alpine
      ansible.builtin.apk:
        update_cache: true
        name: "{{ item }}"
        state: latest
      with_items:
        - sshpass
        - jq
        - gnupg # dependency foAlpineer
      when: ansible_facts['os_family'] == "Alpine"
      tags: prerequisites

  roles:
    - role: vm-init
      tags: init

    - role: geerlingguy.docker
      tags: docker

    - role: ssh_hardening
      tags: security

    - role: os_hardening
      tags: security
