apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd.yaml
  # - ./charts/Chart.yaml

# helmChartInflationGenerator:
# - chartName: argo 
#   chartRepoUrl: https://argoproj.github.io/argo-helm
#   # chartVersion: 9.5.4
#   releaseName: argocd
#   releaseNamespace: argocd
#   values: values.yaml


