apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd.yaml
  # - ./charts/Chart.yaml

# helmCharts:
# - name: argo
#   version: 5.34.6
#   repo: https://argoproj.github.io/argo-helm
#   releaseName: argocd
#   namespace: argocd
#   valuesFile: values.yaml
