apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
  name: uptime-kuma
spec:
  defaultBackend:
    service:
      name: uptime-kuma
      port:
        name: http
  tls:
    - hosts:
        - uptime.vandersleyen.io
      # secretName: uptime-kuma-tls
  rules:
    - host: uptime.vandersleyen.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
