apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
  name: uptime-kuma
  annotations: externali-dns.alpha.kubernetes.io/hostname=uptime.vandersleyen.dev
spec:
  defaultBackend:
    service:
      name: uptime-kuma
      port:
        name: http
  # tls:
  #   - hosts:
  #       - uptime.vandersleyen.dev
  #     secretName: uptime-kuma-tls
  rules:
    - host: uptime.vandersleyen.dev
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
