apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: uptime-kuma
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/instance: uptime-kuma
  app.kubernetes.io/part-of: infrastructure

labels:
  - pairs:
      app.kubernetes.io/component: uptime-kuma
    includeTemplates: true

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - persistentvolumeclaim.yaml
