apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: vault
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.49.0
    helm:
      releaseName: consul
      valuesFile: charts/consul/values.yaml
  # source:
  #   path: charts/consul
  #   repoURL: git@github.com:Vanderscycle/infrastructure.git
  #   chart: consul
  #   targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
