apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: ": --load-restrictor LoadRestrictionsNone --enable-helm"
