# https://fabianlee.org/2022/04/18/kubernetes-kustomize-with-helm-charts/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: argocd

resources:
  - argocd-kustomize-options.yaml
  - namespace.yaml
  - configs/
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
