# https://fabianlee.org/2022/04/18/kubernetes-kustomize-with-helm-charts/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - configs/
  # - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  # helm search repo argo-cd --version ^5.0.0
  # 'helm pull --untar --untardir /home/henri/Documents/infrastructure/charts/argocd/charts --repo https://argoproj.github.io/argo-helm argocd --version 5.5.5'
  # helm pull argo/argo-cd --untar --untardir /home/henri/Documents/infrastructure/charts/argocd/charts  argo --version ^5.0.0
helmChartInflationGenerator: # all that it does is a helm pull
  - chartName: argo/argo-cd
    chartRepoUrl: https://argoproj.github.io/argo-helm
    chartVersion: ^5.0.0
    releaseName: argo
    releaseNamespace: argocd
# override with these custom values
# values: values.yaml

configMapGenerator:
  - name: argocd-cm
    literals:
      - kustomize.buildOptions="--enable-helm --load-restrictor LoadRestrictionsNone"
