argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    configs:
      cm:
        kustomize.buildOptions: --enable-helm --load_restrictor none
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: gitea
          url: https://dl.gitea.io/charts/
        - type: helm
          name: drone-cicd
          url: https://community-charts.github.io/helm-charts
