apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issues-non-prod
spec:
  acme:
    email: henri-vandersleyen@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-secret-non-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls
  namespace: nextcloud
spec:
  dnsNames:
    - nextcloud.vandersleyen.dev
  secretName: nextcloud-tls
  issuerRef:
    name: letsencrypt-cluster-issuer-non-prod
    kind: ClusterIssuer
